### ISSUE TITLE
Not Showing Bio-Metric Dialog on Android P devices

### ISSUE THREAD

**Issue by parthdesai1208** [anitaa1990/Biometric-Auth-Sample#10] opened 2019-04-21 10:55 UTC
Dialog appeared on Devices which having below Android P version. but not appeared on P devices.

**Comment by Sammekl** [comment] 2019-04-29 14:32
Do you encounter this issue on an emulator or physical device? I cannot reproduce this issue. Please check the BiometricCallback methods to see the actual error

**Comment by parthdesai1208** [comment] 2019-05-03 13:26
@Sammekl  I faced this issue on my one plus (6T) device. A biometric dialog did not appear.

**Comment by Sammekl** [comment] 2019-05-08 11:28
> @Sammekl I faced this issue on my one plus (6T) device. A biometric dialog did not appear.

That's weird, I'm using a OnePlus 5T myself on Android Pie, no issues whatsoever. Nothing to see in the logs? Did you debug to see if all the code is called in order to show the dialog?

Edit: Probably related to inscreen fingerprint?

**Comment by parthdesai1208** [comment] 2019-05-09 07:31
@Sammekl here I attach a screenshot of the app. as you can see dialog is missing but rest of the things working perfectly.
![Screenshot_20190509-125647](https://user-images.githubusercontent.com/28099478/57435213-680fcd80-725a-11e9-90c9-b5e6306fa8e2.jpg)

**Comment by zakuby** [comment] 2019-05-10 11:30
Hi @Sammekl , currently i faced the same issue on OnePlus 6T (Pie), its doesn't show Biometric Dialog (title, subtitle, description, and cancelation button) instead its just show an Image.

![photo_2019-05-10 17 01 28](https://user-images.githubusercontent.com/13521955/57524027-d3d46200-7350-11e9-9b13-8bdf7ba07c43.jpeg)

However on other devices(Samsung Galaxy S8) with Android Pie, its show the Biometric Dialog.

![photo_2019-05-10 18 25 56](https://user-images.githubusercontent.com/13521955/57524140-1f870b80-7351-11e9-8837-342817764d1a.jpeg)

Its is possible to show Dialog V23 and Biometric (Default of OnePlus 6T) at the same time ?
I looked up to [OVO](https://play.google.com/store/apps/details?id=ovo.id&hl=en) application its show biometric Oneplus 6T and Dialog V23 at the same time
![photo_2019-05-10 16 53 34](https://user-images.githubusercontent.com/13521955/57524222-607f2000-7351-11e9-975a-59b9d01ffe09.jpeg)

**Comment by DhruvaSambrani** [comment] 2019-05-30 10:24
Look at #5.
Seems to be the same issue. It's only a problem with on-screen fingerprint devices.
How did you do it @Sammekl?

**Comment by Sammekl** [comment] 2019-05-30 10:33
You are right, this is probably an issue at OnePlus's end. I've encountered the same issue on my new OnePlus 7 Pro. It does work on the Samsung S10 with inscreen-fingerprint. 

It's not just this library which has issues, it's a bug when using BiometricPrompt on OnePlus. I've already reported this issue to OnePlus last week

**Edit:**
I did a test using the default Android BiometricPrompt implementation and can confirm that this is not a library issue. The same issue occurs with the following code:
```
BiometricPrompt biometricPrompt = new BiometricPrompt.Builder(getApplicationContext())
                .setTitle("Title")
                .setNegativeButton("Text", this.getMainExecutor(), (dialog, which) -> {

                })
                .setDescription("Description")
                .setSubtitle("Subtitle")
                .build();

biometricPrompt.authenticate(new CancellationSignal(), this.getMainExecutor(), new 
     BiometricPrompt.AuthenticationCallback() {
                @Override
                public void onAuthenticationError(int errorCode, CharSequence errString) {
                    super.onAuthenticationError(errorCode, errString);
                }

                @Override
                public void onAuthenticationHelp(int helpCode, CharSequence helpString) {
                    super.onAuthenticationHelp(helpCode, helpString);
                }

                @Override
                public void onAuthenticationSucceeded(BiometricPrompt.AuthenticationResult result) {
                    super.onAuthenticationSucceeded(result);
                }

                @Override
                public void onAuthenticationFailed() {
                    super.onAuthenticationFailed();
                }
            });
```

**Comment by DhruvaSambrani** [comment] 2019-05-30 10:34
Then close the issue?

**Comment by Sammekl** [comment] 2019-05-30 10:43
I am not a contributor to this repo so I can't.

@anitaa1990

**Closed as completed** 2019-05-31 06:02 UTC
